import csv

def main():
    # Ask for user inputs
    greyScale = input("Enable grayscale? Enter TRUE/FALSE: ")
    blur = input("Blur amount? (Enter a number, e.g. 0, 1, 2...): ")
    x_size = input("Width (x_size): ")
    y_size = input("Height (y_size): ")

    # We set RUN to "TRUE" so your R script knows to process the request
    run_val = "TRUE"
    
    # The URL field will be generated by your R script, so we can leave it blank or use a placeholder
    url_placeholder = ""

    # Write to request.csv with a header
    with open("request.csv", "w", newline="") as csv_file:
        writer = csv.writer(csv_file)
        # Adjust headers to match your existing CSV structure
        header = ["RUN", "greyScale", "blur", "x_size", "y_size", "URL"]
        writer.writerow(header)
        writer.writerow([run_val, greyScale, blur, x_size, y_size, url_placeholder])
    
    print("request.csv updated successfully!")

if __name__ == "__main__":
    main()
